### ISSUE TITLE
Add Software License

### ISSUE THREAD

**Issue by 0verk1ll** [lukepearson/vscode-extension-cidr-ip-range#3]
Please add a software license to this project to make it possible to be included in the [Open VSX Registry](https://www.eclipse.org/legal/open-vsx-registry-faq/#faq-10-1), which is used by VSCodium (see <https://github.com/VSCodium/vscodium/issues/747#issuecomment-881684649>).

**Comment by lukepearson** [comment]
Thanks for raising this, happy with the GPL3 licence for this repo 👍
