### ISSUE TITLE
Emphasize "invalid" CIDR ranges

### ISSUE THREAD

**Issue by makeacode** [lukepearson/vscode-extension-cidr-ip-range#5]
Have a task to migrate Palo Alto rules to Azure Firewall and there are ranges that the palo accepted but azure does not.

For example:

10.82.187.0/22 needs to be specified as 10.82.184.0/22 for azure to accept it.  though they specify the same logical range azure requires it to be the beginning of the range.

Is it possible to have an option to annotate or signal this somehow? perhaps by changing the coloring?  It would be extremely useful for me.

**Comment by lukepearson** [comment]
Hi, thanks for the suggestion!

Had a go at adding a code action if the CIDR notation does not use the first address in the given range:

<img width="549" alt="highlight" src="https://user-images.githubusercontent.com/2988301/180523991-8bffa7d5-8f09-403e-99aa-a4e1afa20a91.png">


The hover state shows what the valid CIDR range should look like

<img width="585" alt="hover" src="https://user-images.githubusercontent.com/2988301/180524412-ea4c3783-99ce-4474-b845-55020a26e309.png">

There is also a quick fix that will apply the correct CIDR range

<img width="272" alt="quickfix" src="https://user-images.githubusercontent.com/2988301/180524815-35ead184-2994-4b73-8726-93256f689639.png">


I'm thinking this would sit behind a toggle, which would default to `false`, so you would have to enable it in the VSCode settings.json file with 
```
"cidr-ip-range.enableStrict": true
```

Let me know if this is what you had in mind and i'll create a PR!

**Comment by makeacode** [comment]
Wow.  This is excellent and exactly what I was looking for.  I had
considered submitting a PR this weekend but glad you beat me to it as I
like this solution better than what I was imagining.

**Comment by lukepearson** [comment]
Thanks, glad to hear you're happy with the solution! I've created a PR #6 so if you're happy with it then I'll go ahead and merge it in and publish the new version.

**Comment by makeacode** [comment]
yeah, i'd love to give it a try.  i think my team still has more migration work coming so this will be extremely helpful.

**Comment by lukepearson** [comment]
I've published the new version. It can take a while to show up in VSCode, so not sure when it will be available, but feel free to raise more issues here if you encounter any problems. Hope your migration goes smoothly!
